### ISSUE TITLE
Don`t routing IPv6 and WebRTC leak

### ISSUE THREAD

**Issue by TSpodeneyko** [jomertix/marzban-tools#1]
when using routing with domestic and foreign servers, WebRTC leakage and loss of IPv6 address occurs
![photo_2024-01-26_11-14-17](https://github.com/jomertix/marzban-tools/assets/45203444/4c9bc47f-439b-468e-a65b-0500f87a2339)

**Comment by jomertix** [comment]
Hello. The configs only provides an example of using traffic routing using the VLESS protocol. 

WebRTC is a browser technology and it is possible to fix an IP leak only on the client side, not the server.
